services:
  # Backend API service
  - type: web
    name: retinopathy-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --log-level info --timeout 300 --workers 1 --threads 2 --max-requests 3 --max-requests-jitter 2 --access-logfile - --error-logfile - --keep-alive 5 --preload
    autoDeploy: true
    # Konfigurasi untuk model berukuran besar
    disk:
      name: model-storage
      mountPath: /opt/render/project/src
      sizeGB: 5
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 3
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: true
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SIMULATION_MODE_ENABLED
        value: false
      - key: MODEL_PATH
        value: /opt/render/project/src/model-Retinopaty.h5
      - key: GUNICORN_CMD_ARGS
        value: "--log-level info --timeout 300 --workers 1 --threads 2 --max-requests 3 --preload"
    healthCheckPath: /health
    healthCheckTimeout: 10
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - model-Retinopaty.h5
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-apt 