services:
  - type: web
    name: retinascan-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SIMULATION_MODE
        value: 1
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: true
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
    autoDeploy: true