services:
  - type: web
    name: flask-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SIMULATION_MODE
        value: "0"
      - key: FORCE_MODEL
        value: "1"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: model-storage
      mountPath: /app/models
      sizeGB: 1
    autoDeploy: true